- openmrs/README.md
Add info about python to run Profile Manager on the server
> Add Python Info to wiki

- openmrs/api/pom.xml
- openmrs/api/src/main/java/org/projectbuendia/openmrs/api/ProjectBuendiaService.java
- openmrs/api/src/main/java/org/projectbuendia/openmrs/api/db/ProjectBuendiaDAO.java
- openmrs/api/src/main/java/org/projectbuendia/openmrs/api/db/hibernate/HibernateProjectBuendiaDAO.java
- openmrs/api/src/main/java/org/projectbuendia/openmrs/api/impl/ProjectBuendiaServiceImpl.java
- openmrs/api/src/main/resources/moduleApplicationContext.xml
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/Utils.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/EncounterResource.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/PatientResource.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/RequestUtil.java
Reviewed on PR #20, this is the same code but targeting a different branch.
> Incremental sync for encounters.

- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/PatientResource.java
Corresponding client change: https://github.com/projectbuendia/client/pull/126
> Rename Gender --> Sex as per TODO

- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/PatientResource.java
Also add logging for sync requests.
> Refactor PatientResource to use newer incremental sync utilities.

- openmrs/api/src/main/java/org/projectbuendia/openmrs/api/ProjectBuendiaService.java
- openmrs/api/src/main/java/org/projectbuendia/openmrs/api/db/ProjectBuendiaDAO.java
- openmrs/api/src/main/java/org/projectbuendia/openmrs/api/db/hibernate/HibernateProjectBuendiaDAO.java
- openmrs/api/src/main/java/org/projectbuendia/openmrs/api/impl/ProjectBuendiaServiceImpl.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/OrderResource.java
Probably best to review this commit-by-commit; the first two commits are cleanup only and the third is the actual incremental sync logic.
> Incremental Sync for Orders.

- tools/profile_apply
Fixes https://github.com/projectbuendia/client/issues/198.
> Truncate form UUIDs to 38 chars in `profile_apply`.

- tools/profile_apply
*** THIS NEED TO BE MERGED ALONGSIDE WITH THE CLIENT PR ***
Chart divider for multiple charts.
> Multiple Charts

- tools/profile_apply
> Fix `profile_apply` script (sorry!).

- openmrs/omod/src/main/java/org/openmrs/projectbuendia/servlet/DataExportServlet.java
Fixed patient birth date bug and added try/catch for non stop exporting.
This fixes #53
> Fix CSV Export

- openmrs/omod/src/main/java/org/openmrs/projectbuendia/Utils.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/OrderResource.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/XformInstanceResource.java
This is a partial fix for projectbuendia/client#214.
Note that this PR depends on work from pull request #57, only the latest commit 7936b34 should be reviewed as part of this pull request.
> Attribute Orders to the users that created them.

- tools/profile_apply
This fixes #204 -> "Failed to fetch form from server" problem.
> Create default form section [invisible]

- tools/profile_apply
Changes how yes_no fields are created so they only have options yes and no, and not unknown.
Introduce new yes_no_unknown field type that allows for all three options.
> In profile, make yes_no really mean yes or no and introduce yes_no_unknown

- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/PatientResource.java
This is part of the fix for the issue:
https://github.com/projectbuendia/client/issues/176
> Enable like search.

- openmrs/omod/src/main/java/org/openmrs/projectbuendia/servlet/DataExportServlet.java
The default behavior of the new CSV Export is to merge encounters that are near each other by 30 minutes.
Each encounter within 30 minutes will be merged to the previous one overlapping the old value with the most recent one.
The interval can be customized passing a value in the url like:
http://localhost:9000/openmrs/moduleServlet/buendiadata?interval=120
> New CSV Export

- openmrs/omod/src/main/java/org/openmrs/projectbuendia/servlet/DataExportServlet.java
Merging if not overlapping observations except text.
If Text concatenate. 
Text observations have the time of the encounter concatenated.
> Selectively Merging Encounters on CSV Export

- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/EncounterResource.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/XformInstanceResource.java
Partial fix for https://github.com/projectbuendia/client/issues/125
> Send complete Encounter information in response to Xform submission.

- openmrs/omod/src/main/java/org/projectbuendia/openmrs/extension/html/AdminList.java
- openmrs/omod/src/main/java/org/projectbuendia/openmrs/web/controller/PrintCharts.java
- openmrs/omod/src/main/webapp/print-charts.jsp
- openmrs/omod/src/main/webapp/printable.jsp
Merging into the pilot branch so we can try it out before piloting in ITFC.
Thanks @llvasconcellos!
> Printable Charts v1

- tools/profile_apply
This is the server side implementation for the pivotal story:
***Allow profile for a chart to specify one column per encounter (or per minute)***
* Added the profile format column to the [chart_divider] field description.
This is the profile I'm using for testing it:
[nutrition-atfc-101-v3.txt](https://github.com/projectbuendia/buendia/files/150180/nutrition-atfc-101-v3.txt)
> Chart Column Interval Config

- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/OrderResource.java
- openmrs/omod/src/main/java/org/projectbuendia/openmrs/extension/html/AdminList.java
- openmrs/omod/src/main/java/org/projectbuendia/openmrs/web/controller/PrintCharts.java
- openmrs/omod/src/main/webapp/print-charts.jsp
- openmrs/omod/src/main/webapp/printable.jsp
- packages/buendia-backup/data/usr/bin/buendia-backup
Still a work in progress but It can be merged.
> Printable Charts

- openmrs/README-debian.md
- openmrs/README.md
- tools/apt/README.md
- tools/apt/apt.conf.d/99norecommends
- tools/apt/preferences.d/openjdk-7
- tools/apt/sources.list.d/openjdk-7.list
- tools/openmrs_setup
> Document installation of Buendia on fresh Debian stretch

- recovery/How_to_recover_access_to_resources.md
updated instructions for recovery
> updated instructions for recovery

- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/PatientResource.java
- openmrs/omod/src/test/java/org/openmrs/projectbuendia/webservices/rest/PatientResourceTest.java
- openmrs/omod/src/test/resources/org/openmrs/projectbuendia/webservices/rest/base-test-data.xml
- openmrs/omod/src/test/resources/org/openmrs/projectbuendia/webservices/rest/patient-test-data.xml
This adds some simple tests for the PatientResource, in particular setting and changing the location of a patient.
> Add PatientResource tests

- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/AbstractReadOnlyResource.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/LocationResource.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/Logger.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/OrderResource.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/PatientResource.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/RequestLogger.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/UserResource.java
- packages/buendia-utils/data/usr/bin/buendia-status
There are also many small improvements to logging here (inclusion of more useful information, reduction of redundant information).
> Log HTTP requests so they can be seen on the dashboard

- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ObservationResource.java
Previously we did not log any requests at all in the observations resource, probably because we were afraid of the log data getting too big.  This PR abbreviates the data if it's too long, and then enables logging for these requests.
> Add logging for /observations requests (abbreviate long replies).

- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/PatientResource.java
This fixes a bug in handling of the two identifier namespaces (LOCAL and MSF) that prevented editing of patients with LOCAL identifiers.
> Fix editing patients with locally-generated identifiers.

- openmrs/omod/src/main/java/org/openmrs/projectbuendia/Utils.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/servlet/DataExportServlet.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/AbstractReadOnlyResource.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/EncounterResource.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ObservationResource.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ObservationUtils.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/PatientResource.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/RequestUtil.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ResponseUtil.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/SyncTokenUtils.java
- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/XformInstanceResource.java
- openmrs/omod/src/test/java/org/openmrs/projectbuendia/webservices/rest/SyncTokenUtilsTest.java
- openmrs/omod/src/test/java/org/openmrs/projectbuendia/webservices/rest/XformInstanceResourceTest.java
This is a small change to clean up our use of date parsing functions in `Utils`.
> Tidy up date parsing functions.

- openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/UserResource.java
The guest provider now gets a stable, readable UUID following our usual naming convention, and the creation of the guest provider is simplified.
> Make the guest provider recognizable to the client by UUID

- packages/buendia-pkgserver/data/usr/bin/buendia-pkgserver-import
- packages/buendia-pkgserver/data/usr/share/buendia/tests/40-pkgserver-running-safe
- packages/buendia-pkgserver/data/usr/share/buendia/tests/50-pkgserver-commands-safe
- packages/buendia-pkgserver/data/usr/share/buendia/tests/60-pkgserver-import
- packages/buendia-utils/data/usr/share/buendia/test-harness.sh
Also squash #145 for good measure.
> Add integration tests for buendia-pkgserver

- tools/profile_apply
This extends the profile syntax in preparation for defining the fixed tiles at the top of the screen in the profile.
> Profile syntax for fixed tiles

- .circleci/config.yml
- packages/buendia-backup/data/usr/share/buendia/tests/50-backup-locked-safe
- packages/buendia-backup/data/usr/share/buendia/tests/60-backup-and-restore
- packages/buendia-dashboard/data/usr/share/buendia/tests/40-dashboard-running-safe
- packages/buendia-server/data/usr/share/buendia/config.d/70-server
- packages/buendia-site-cloud-demo/Makefile
- packages/buendia-site-cloud-demo/control/control.template
- packages/buendia-site-cloud-demo/control/postinst
- packages/buendia-site-cloud-demo/data/usr/share/buendia/packages.list.d/site
- packages/buendia-site-cloud-demo/data/usr/share/buendia/site/40-site
- packages/buendia-site-test-integration/control/control.template
- packages/buendia-tomcat7/data/usr/share/buendia/diversions/etc/default/tomcat7
- packages/buendia-utils/data/usr/share/buendia/test-harness.sh
- tools/iso/preseed.cfg
- tools/vagrant/provision-build.sh
- tools/vagrant/provision-testing.sh
Somehow in the release process for 0.16 the commits for PR #209 and #210 were removed from the dev branch. This PR replaces them.
> Replace commits from #209 and #210
