openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/LocationResource.java
openmrs/omod/src/main/java/org/projectbuendia/openmrs/web/controller/ProfileManager.java
packages/buendia-db-init/data/usr/share/buendia/db/site-msf-chad-bokoro.sql
packages/buendia-mysql-python/Makefile
packages/buendia-mysql-python/control/control.template
packages/buendia-mysql-python/control/preinst.template

The issue with locations not showing up was because it is hardcoded to use a "Facility Kailahun" location with a specific UUID as the root location.
The app looks for sub-sub-locations within that, expecting Facility Kailahun to have zones like "Suspect Zone" within it, and then tents like "S1", "S2", etc. within that.
To fix it, I set the root location for the Chad locations to be the location specified in ROOT_UUID.
I also renamed it to a generic name "ROOT LOCATION" instead of something site-specific.
TODO (later): Improve how this is done so that this stuff is defined in the site-specific config file instead of hard-coded in LocationResource.java.
The next issue is that the profile_apply Python script responsible for applying Buendia profiles in the Project Buendia OpenMRS module …

Fix things so Edison can set itself up for Chad from scratch

---

tools/openmrs_setup

Added creation of files and folders and setting permissions to proper functioning of Profile Manager on developer machines.

Fix dev setup script

---

openmrs/omod/src/main/java/org/projectbuendia/openmrs/web/controller/ProfileManager.java
openmrs/omod/src/main/webapp/profiles.jsp

In depth refactoring for better error handling and displaying on the Profile Manager.
Other refactoring was made to improve profiles.jsp readability.
Also was introduced the ability to setup a custom path for the profile storage folder.
The custom folder configuration must be in openmrs-runtime.properties under profile_manager.profile_dir.
This changes is related to issue #12.

Profile Manager Error Handling

---

tools/openmrs_setup

Previously, `sed` would write to a file named sudo. As of this change, the script writes to the
correct location.
See also: http://stackoverflow.com/q/82256/996592

Fix OSX-specific fatal error in openmrs_setup.

---

openmrs/README.md

Profiles are a critical part of the setup process now, so it's important to make developers aware that they need to apply them when they're getting set up.
See also Wiki Page: https://github.com/projectbuendia/buendia/wiki/Setting-Up-a-Buendia-profile

Add profile information to OpenMRS setup README.

---

openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/EncounterResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/PatientResource.java

Neither of these parameters are used by the client, so they're safe to remove. I'm interested in removing them because they're additional overhead that would otherwise need to be maintained as part of the sync refactor.

Cleanup / Remove unused query params

---

openmrs/api/src/main/java/org/projectbuendia/openmrs/api/ProjectBuendiaService.java
openmrs/api/src/main/java/org/projectbuendia/openmrs/api/db/ProjectBuendiaDAO.java
openmrs/api/src/main/java/org/projectbuendia/openmrs/api/db/hibernate/HibernateProjectBuendiaDAO.java
openmrs/api/src/main/java/org/projectbuendia/openmrs/api/impl/ProjectBuendiaServiceImpl.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/EncounterResource.java

In response to comments on #20, I renamed some API methods from `getEncountersModifiedOnOrAfter` to `getEncountersCreatedAtOrAfter`. I missed a couple of places though.

Cleanup some API method names for better consistency

---

packages/buendia-db-init/data/usr/share/buendia/db/site-dev.sql

All the tests are written assuming Bokoro locations, so the dev setup script should use them too,
so that tests can be run locally.
This is a straight copy-paste of the site-msf-chad-bokoro.sql file.

Change the dev-specific SQL script to use Bokoro locations.

---

tools/clear_server.sql

These tables are huge and we don't need them.  Clearing them significantly speeds up installation/flashing of the server software.

Clear the concept_word and concept_reference_* tables

---

third_party/openmrs-module-xforms/api/src/main/java/org/openmrs/module/xforms/buendia/BuendiaXformBuilderEx.java

This PR fixes [client issue #56](https://github.com/projectbuendia/client/issues/56).
Here are my thoughts about this change:
* The condition which checks the repeated name between section and label is
````
if (formField.getParent() != null && fieldTokens.values().contains(name)) {
```
The form (label) has to have a parent (section) and the section name matches the label name.
If so, the could would try to generate another name key, concatenating the section name and the label name (which will be the same).
```
String parentName = fieldTokens.get(formField.getParent());
String token = parentName + "_" + name;
```
Then the code checks if this new token was already populated in `bindings` by `BuendiaXformBuilder.parseTemplate` method. If not, it generates another different token and …

Fix client issue #56. App crashes when profile section name and profile label name are equal.

---

packages/buendia-update/data/usr/bin/buendia-update

We had a problem where Jenkins wasn't pushing new builds to dev.projectbuendia.org, and we had no
idea because the buendia-update script was squelching errors.
This change removes some of the squelching such that update failures cause Jenkins to actually show
failures.

Make the buendia-update script actually error if one of its steps fails.

---

openmrs/api/src/main/java/org/projectbuendia/openmrs/PatientSyncParameters.java
openmrs/api/src/main/java/org/projectbuendia/openmrs/api/ProjectBuendiaService.java
openmrs/api/src/main/java/org/projectbuendia/openmrs/api/SyncToken.java
openmrs/api/src/main/java/org/projectbuendia/openmrs/api/db/ProjectBuendiaDAO.java
openmrs/api/src/main/java/org/projectbuendia/openmrs/api/db/SyncPage.java
openmrs/api/src/main/java/org/projectbuendia/openmrs/api/db/hibernate/HibernateProjectBuendiaDAO.java
openmrs/api/src/main/java/org/projectbuendia/openmrs/api/impl/ProjectBuendiaServiceImpl.java
openmrs/api/src/main/resources/PatientSyncParameters.hbm.xml
openmrs/api/src/main/resources/liquibase.xml
openmrs/api/src/test/java/org/projectbuendia/openmrs/api/db/hibernate/HibernateProjectBuendiaDAOTest.java
openmrs/api/src/test/resources/TestingApplicationContext.xml
openmrs/api/src/test/resources/buendia-hibernate.cfg.xml
openmrs/api/src/test/resources/org/projectbuendia/openmrs/include/patientDataSetNoDuplicateTimestamps.xml
openmrs/api/src/test/resources/org/projectbuendia/openmrs/include/patientDataSetWithDuplicateTimestamps.xml
openmrs/api/src/test/resources/org/projectbuendia/openmrs/include/patientDataSetWithVoids.xml
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/PatientResource.java
openmrs/omod/src/main/resources/config.xml

This is a pretty different approach to the old PR #39.
The old approach:
- created a new DB column on the `person` table, 
- updated that column with a SQL trigger,
- fought against Hibernate to be able to use that column in WHERE and ORDER BY clauses.
The new approach:
- creates a new DB _table_, that's keyed off the `person` table
- updates records in that table with a SQL trigger (similarly to the old approach)
- Accesses those records using Hibernate - Hibernate treats the sync data as actual objects now, which makes them significantly easier to work with.
I rewrote this code using the new approach because it seemed like the old approach wasn't testable. For tests, OpenMRS uses an in-memory database, which has its schema defined by Hibernate's ideas about what the tables should look …

Implement Patient Sync pagination in the DAO

---

openmrs/omod/src/main/java/org/openmrs/projectbuendia/Utils.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ObservationResource.java

This allows clients to properly attribute observations to a specific user.
Note that we're especially carefully not to crash sync if an observation was recorded by someone
that doesn't exist in a way that's compatible with the Buendia model of a 'User'.
Each Buendia user has the following three objects in OpenMRS:
- A Person, which contains information such as the person's name
- A User, which contains login credentials (though Buendia doesn't really populate these properly)
- A Provider, which is the OpenMRS representation of a person who administers orders.
When users are synced from the server to the client, the Provider ID gets sent down at the moment,
so we have to do a bit of work to convert providers into users and back throughout.

Add the enterer's UUID to observations sent from the server.

---

openmrs/api/src/main/resources/liquibase.xml

Patients weren't able to be synced until they were edited, due to a bug in the SQL trigger that
creates entries in the `buendia_patient_sync_map` on person insert.
This change fixes that bug. Fixes https://github.com/projectbuendia/client/issues/187

Fix patients not syncing until an observation was added.

---

openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ConceptResource.java

Previously, secondary concepts in chart fields (any concepts other than the first listed concept)
were not synced to the client. This resulted in the client not knowing how to render these secondary
concepts unless they were also a primary concept in another chart field.
Fixes https://github.com/projectbuendia/client/issues/202.

Sync secondary concepts that aren't referenced anywhere else.

---

openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/EncounterResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ObservationResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ObservationsHandler.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/PatientResource.java

- Allow free-text observations to be submitted as part of encounters.
- Attribute encounters to the user who entered them.
- Standardise the way observations are represented in encounters, so they more closely match the
representation used for observation sync.

Server-side changes required to support notes panel.

---

openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ChartResource.java

This property was being ignored resulting all fields set to false on the client.

Outputs the required property of fields.

---

packages/buendia-dashboard/data/usr/share/buendia/dashboard/index

Some users have custom DNS servers, which ruins the whole "navigate to `server/`" thing. So instead,
we change the internal, cross-port links to point at the IP of the server (10.0.0.50), and should
inform users to try `server/` or `10.0.0.50` if that doesn't work.

Fix links in dashboard so they work without our DNS server.

---

packages/buendia-backup/data/usr/bin/buendia-backup

OpenMRS logs change frequently, and if the file changes whilst being `tar`'d, tar quits with an
error. This was causing backups to fail about 25% of the time in our pilot deployment.

Exclude OpenMRS logs from the backup.

---

tools/profile_apply

It was almost certainly introduced by accident, because our users are hand-writing CSV files.
Whitespace at the end of strings is indetectable to users, but breaks ODK collect's form persistence
feature, because it is trimming concept labels at some stage and expecting the (trimmed) concept
label to match the label that we supply.

Strip whitespace from all cells in the profile_apply script.

---

openmrs/omod/src/main/java/org/openmrs/projectbuendia/servlet/DataExportServlet.java

Note that now we have a ordering parameter. The default behavior is to order columns to mach the patient chart but if the ***sortByUUID=true*** parameter is added the columns will be ordered by the UUID and that's the previous behavior.
**UPDATE**
The last commit added a parameter called ***idsAndUuids***. This parameter, when true, adds the 2 extra columns for each concepts (ID and UUID). It defaults to false.

CSV Export Enhancements

---

.travis.yml
tools/travis-ci/choose_version_number.sh
tools/travis-ci/update_build_server.sh

This is pretty complicated and I'm not entirely sure if it works yet. Here's the gist:
- I created a repo `projectbuendia/builds`. It's going to act as our new build server.
- When a build on either the `dev` or `master` branch finishes, it gets pushed to the builds repo.
- The builds repo works out to be a flat-file debian package server, so it should be accessible directly as `http://projectbuendia.github.io/builds`.
But we won't know for sure until I've submitted :)

Add build server pushes to travis config

---

.circleci/Makefile
.circleci/config.yml
tools/docker/Dockerfile
tools/docker/Makefile
tools/docker/README.md

* Add `tools/docker/` to create a minimal Debian stretch image with OpenJDK 7 and the other prerequisites for building our Debian packages. A Makefile builds and ships the image.
* Add `.circleci/` to provide configuration for building Debian packages in CircleCI. A Makefile there can be optionally used with the [CircleCI local-cli tools](https://support.circleci.com/hc/en-us/articles/360006735753-Validating-CircleCI-configuration-files-YAML-linting-issues-etc-) to lint `config.yml` before committing/pushing.
In the process, I also set up a [Docker Hub repository](https://cloud.docker.com/u/projectbuendia/repository/docker/projectbuendia/debian-stretch) for our Docker images. The credentials have been put in the project credential store.
This branch [builds …

Add CircleCI support.

---

tools/apt/preferences.d/tomcat7
tools/apt/sources.list.d/tomcat7.list

Turns out, Tomcat 7 doesn't live in any of the Debian repos we've already documented. This PR adds additional config files to `tools/apt/` (to be installed in `/etc/apt` on a stretch system) to allow `apt-get install buendia-server` to pull in the right dependencies.

Add apt dependencies for Tomcat 7.

---

tools/diffdeb

This is necessary now that we're building packages in CI. CircleCI regularly makes a fresh checkout of the code base, with the result that file timestamps are different from one CI run to the next, because git doesn't set them.
This change ensures that file timestamps are never a reason in and of themselves to retain an otherwise unchanged Debian package.
This PR also adds a verbose flag to `diffdeb` for debugging purposes. This flag shouldn't be used by automated processes, since it leaves the temporary directories intact for manual investigation.

 Change diffdeb so as to ignore file timestamps.

---

.circleci/config.yml
tools/README.md
tools/fetch_circleci_artifacts
tools/trigger_archive_update

As an aid to development, this PR adds the ability to trigger a rebuild of the 'stable' or 'unstable' package suites, using the `tools/trigger_archive_update` script and a [valid CircleCI API token](https://circleci.com/docs/2.0/managing-api-tokens/#creating-a-personal-api-token) in the `$CIRCLE_API_TOKEN` environment variable.
Since the manual rebuild is running without the benefit of a successful build leaving packages in the CircleCI workspace, this PR also includes a generic Python script which fetches the build artifacts from the latest successful build of the given branch. This script is called from CI whenever it appears that the apt repo rebuild has been triggered manually, using a [CircleCI API project token](https://circleci.com/docs/2.0/managing-api-tokens/#creating-a-project-ap …

Add a manual trigger to rebuild the Debian package archive.

---

.circleci/config.yml
packages/buendia-server/Makefile
packages/buendia-utils/Makefile
tools/docker/Dockerfile
tools/docker/Makefile

Although `diffdeb` now disregards file timestamps, it will still return true for files that contain internal file directories, e.g. `.zip`, `.jar`, and `.omod` files.
This PR uses the [`git restore-mtime`](https://github.com/MestreLion/git-tools#git-restore-mtime) tool to set the modification times of the files in the local repository to the mtime of the file in its last commit.
This fixes the problem for just about everything except the `.omod` files, which contain freshly build `.class` and `.properties` files every time, and will defy this otherwise simplistic approach to functional comparison.
As a result, this PR also switches off automatic apt repo rebuilds for the `dev` branch of this repository, so that we don't fill up [our apt archive](http://github.com/projectbuendia/builds) …

Fix mtimes of build dependencies.

---

tools/README.md
tools/apt/preferences.d/openjdk-7-all
tools/apt/preferences.d/openjdk-7-amd64
tools/apt/preferences.d/openjdk-7-i386
tools/download_java_deps
tools/index_debs
tools/openjdk-7.md
tools/vagrant/Vagrantfile
tools/vagrant/provision-server.sh

See [the documentation](https://github.com/projectbuendia/buendia/blob/2e6fd279/tools/openjdk-7.md) for details on how this all is supposed to work.

Document the static inclusion in projectbuendia/builds of the "java" package component.

---

.circleci/config.yml
tools/fetch_circleci_artifacts
tools/trigger_archive_update

The (previously untestable) code path in our CircleCI code path did not successfully trigger the `apt-archive` job to update the `stable` suite in the projectbuendia.org/builds apt repository when we (successfully) [built packages for the `v0.10.0` release](https://circleci.com/gh/projectbuendia/buendia/185) in CI.
This PR provides the necessary code to allow a post-facto manual rebuild of the stable suite in CI. This process was carried out successfully in [CircleCI job 193](https://circleci.com/gh/projectbuendia/buendia/193), which brought the apt archive up to date with the v0.10.0 release of the buendia server.
The purpose of this PR is merely to pull the correct configuration and tools into the `dev` branch, so that the next release will build _and_ update the apt repository for the …

Fix tagged builds.

---

.circleci/config.yml
tools/README.md
tools/purge_older_packages
tools/trigger_archive_update

In order to keep the projectbuendia/builds repo from growing unwieldy from new packages added with each dev build, this PR adds a `purge_older_packages` tool and a CI configuration that calls it nightly at 2am to permanently remove all but the 3 newest packages from the unstable suite in that Git repo. The file removal is performed using the [BFG utility](https://rtyley.github.io/bfg-repo-cleaner/). The stable suite in any event is left untouched.
I tested this manually in [CircleCI build #241](https://circleci.com/gh/projectbuendia/buendia/241) with the attached changes to `trigger_archive_update` and the purge ran successfully, bringing the repo size down from to >1.5G to <650M.
With this change, we are also dropping the manual approval step for unstable repo updates included in #122. …

Configure CI to purge all but the 3 newest dev builds

---

tools/vagrant/Vagrantfile
tools/vagrant/provision-server.sh

Only applies to the canned server VM config, i.e. `vagrant up server`. Enables testers to run a server in Vagrant and connect from an Android client on the local Wi-Fi.
This PR also includes a patch to keep the Vagrant provisioned sources.list from being blown away by the Buendia Debian package install.

Expose port 9000 in Vagrant for testing.

---

openmrs/api/src/main/resources/liquibase.xml
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ConceptResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/EncounterResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ObservationResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ObservationsHandler.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/PatientResource.java
tools/profile_apply

This brings over:
- Fix for patients not syncing until they have been edited once.
- Sync secondary concepts used in chart rendering.
- Introduce the yes_no_unknown type, and make yes_no mean only yes or no.
- Add server changes to support the notes field in encounters.

Cherry-pick various fixes from the 2016-dev branch

---

.circleci/config.yml
packages/buendia-db-migrate/data/usr/bin/buendia-db-migrate
tools/dedupdeb

After this is merged to `dev`, let's do a `0.12.1` release.  @schuyler  Anything else we need to do to clear everything up?

Allow no-op migration among versions 0.9, 0.10, 0.11, 0.12.

---

packages/buendia-pkgserver/data/usr/bin/buendia-pkgserver-import

In #108 I brought my changes to `tools/index_debs` into `buendia-pkgserver`, and in 9eb9b671, modified `buendia-pkgserver-import` to add the suite argument to the call to `index_debs`. However, this change broke the former script as the package repo directory was not structured with suites in separate subdirectories.
This PR fixes that update by ensuring that `/usr/share/buendia/packages` ends up with the new packages copied into the appropriate suite subdirectory, as `index_debs` now expects.
I have also (manually) confirmed that with this change, `buendia-pkgserver-import` will take a bundle ZIP, and:
1. copy any `.deb` files from the bundle into `/usr/share/buendia/packages/` and reindex them
1. copy any `NN-configuration` files into `/usr/share/buendia/site/`
1. run `commands.sh` if …

Ensure that buendia-pkgserver / buendia-update still work.

---

packages/buendia-backup/data/etc/cron.d/buendia-backup
packages/buendia-dashboard/data/etc/cron.d/buendia-dashboard
packages/buendia-monitoring/data/etc/cron.d/buendia-monitoring
packages/buendia-mysql/data/etc/cron.d/buendia-mysql
packages/buendia-networking/data/etc/cron.d/buendia-networking
packages/buendia-pkgserver/data/etc/cron.d/buendia-pkgserver
packages/buendia-server/data/etc/cron.d/buendia-server
packages/buendia-tomcat7/data/etc/cron.d/buendia-tomcat7
packages/buendia-update/data/etc/cron.d/buendia-update
packages/buendia-utils/control/postinst
packages/buendia-utils/control/prerm

Basically add an empty "MAILTO=" line to /etc/crontab when installing buendia-utils, if no MAILTO= line has been set.
Since we can't know if this line was added by us or not on postrm, just echo a warning to that effect.
Intended as a fix to #132. Tested manually in Vagrant.
cc @zestyping for architectural review

Ensure that cron doesn't fill up root's mail spool with cron job outputs.

---

packages/buendia-networking/control/prerm
packages/buendia-networking/data/usr/bin/buendia-update-hosts
packages/buendia-networking/data/usr/share/buendia/config.d/networking
packages/buendia-networking/data/usr/share/buendia/diversions/etc/dnsmasq.conf
packages/buendia-networking/data/usr/share/buendia/site/10-networking
packages/buendia-site-test/data/usr/share/buendia/site/40-site
packages/buendia-utils/data/usr/share/buendia/systemd/reboot-check.timer

This set of changes more or less ensures that a properly configured NUC can get on the network at boot and stay there.
* Add configuration of DHCP ranges to `$NETWORKING_DHCP_RANGE` and disable serving DHCP if this is not set
* Ensure that `/etc/hosts` and `dnsmasq` (if needed) get a refresh every time a network interface comes up
* Don't automatically bring up the Ethernet device on DHCP if there's a chance it might fail; this seems to cause the networking service to die before it gets to setting up the WPA connection on the wireless interface.
* Other minor bits of polishing.

Fixes to buendia-networking

---

packages/buendia-backup/data/etc/cron.d/buendia-backup
packages/buendia-dashboard/data/etc/cron.d/buendia-dashboard
packages/buendia-monitoring/data/etc/cron.d/buendia-monitoring
packages/buendia-mysql/data/etc/cron.d/buendia-mysql
packages/buendia-networking/data/etc/cron.d/buendia-networking
packages/buendia-pkgserver/data/etc/cron.d/buendia-pkgserver
packages/buendia-server/data/etc/cron.d/buendia-server
packages/buendia-tomcat7/data/etc/cron.d/buendia-tomcat7
packages/buendia-update/data/etc/cron.d/buendia-update
packages/buendia-utils/control/postinst
packages/buendia-utils/control/prerm

Otherwise cron breaks. Fixes #132 & #134.
Confirmed that this solution works in vagrant by checking the contents of `/var/log/buendia/` several minutes after [installing new packages](https://circleci.com/gh/projectbuendia/buendia/355#artifacts/containers/0) from this branch.

Setting an empty MAILTO in crontab requires quotes.

---

packages/buendia-monitoring/data/usr/share/buendia/diversions/etc/logrotate.conf

We're not running a mail server here, so this otherwise unorthodox treatment of the UNIX mail spool has the advantage of being a consistent and reliable way to ensure that `/var/mail` never fills up the disk.

Limit the size of mail spools to 1M (with 5 rotations) using logrotate.

---

tools/iso/README.md
tools/iso/build-buendia-iso
tools/iso/isolinux.cfg
tools/iso/preseed.cfg

This PR contains the components needed to construct a *mostly automated* network installer image for the Buendia server, suitable for burning to USB drive or CD-ROM. This PR depends on #144.
1. Build the installer image as described below, or download it from (somewhere).
2. Write the installer image to bootable media, using e.g.
[balenaEtcher](https://www.balena.io/etcher/) if you're on MacOS.
3. Boot an Intel NUC or other system from the USB media. Unless the machine is
connected to Ethernet with a DHCP server on the network, you will probably
be prompted for networking details. This is a network installer, after all.
3. Follow the prompts related to disk partitioning and boot loader. You can hit
enter at any prompt to use the defaults. On the NUC, this is intended to
result in a …

Add network installation tools for a complete Buendia server

---

packages/buendia-networking/data/usr/share/buendia/config.d/10-networking
packages/buendia-networking/data/usr/share/buendia/site/10-networking

This is a follow-up to PR #138 that moves the selection of network interfaces into `site/10-neworking` where it belong. Closes #142 .
Also, enables DHCP on the wireless interface if no static IP address is set.

Move network interface configuration from config.d to site config

---

openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/DbUtil.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/PatientResource.java

If the ID is not supplied when a new patient is created, the server will generate a local patient ID.  This ID is an integer, but in a namespace separate from client-entered MSF IDs.  Server-generated IDs are represented to the client as prefixed with an asterisk.  Search and retrieval by ID consults the appropriate namespace.

Support server-generated patient IDs

---

openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/XformResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/XmlUtil.java

Issues: Closes #148.
Scope: XForm builder
The server previously had only one static XML `DocumentBuilder` object, shared across all threads.  `DocumentBuilder` is not thread-safe, and will throw exceptions if run concurrently.  With this PR, the XForm builder runs reliably on multiple threads.
I was able to reliably replicate the issue with three processes running continuous requests for an XForm; this would produce a "parse may not be called while parsing" exception every ten seconds or so.
After making this change, I ran six processes simultaneously requesting XForms.  I left it running for 6 minutes, over 2700 requests were served, and there were no errors.

Enable the server to parse more than one XML document at a time

---

third_party/openmrs-module-xforms/api/src/main/java/org/openmrs/module/xforms/buendia/BuendiaXformBuilderEx.java
third_party/openmrs-module-xforms/api/src/main/java/org/openmrs/module/xforms/buendia/XformCustomizer.java

This clears up an ongoing issue we have had, in which the encounter form can show a "Location" selection question, or a "Provider" selection question, or crash on an illegal typecast, or fail to submit because the location or provider information was invalid or missing.
By passing the UUIDs of the providers and locations in the form, the client can definitively select the correct provider and location, and always hide these two questions from the form.

Use UUIDs in the XForm for provider_id and location_id options

---

tools/openmrs_account_setup

This eliminates the hardcoded user, provider, and person_name UUIDs from the server side.  The tool can now be used to create any user account, not just the `buendia` user account.
This is in preparation for sequestering test activities to a special test account.

Enable openmrs_account_setup to create arbitrary accounts.

---

tools/clear_server.sql
tools/openmrs_dump
tools/openmrs_load

With this change, `clear_server.sql` now does a more complete reset to a known state, deleting all custom Buendia concepts as well as locations.  This gives us more confidence that we can get a stuck system into a state where we can successfully apply any profile.

Improve tools (openmrs_dump, openmrs_load, clear_server.sql)

---

openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ChartResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/DbUtil.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/OrderResource.java
tools/profile_apply

Previously, the client requested the chart definition for a specific hardcoded UUID, and that same UUID had to exist on the server.  With this change, this is no longer the case; forms that serve as chart definitions are classified with a special "CHART" encounter type, so they can be discovered without the use of any magic numbers.
Previously as well, there was a global property named `projectbuendia.chartUuids` that purported to identify which forms were charts, but in reality there was nothing to keep it consistent with the rest of the system, resulting in fragility like the possibility of an exception thrown when listing the available charts.  This dependency is now also eliminated.
All Buendia-specific objects that have UUIDs now have UUIDs that follow a recognizable pattern: their …

Eliminate the special hardcoded chart UUID

---

openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ChartResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/DbUtil.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/OrderResource.java
tools/profile_apply

Previously, the client requested the chart definition for a specific hardcoded UUID, and that same UUID had to exist on the server.  With this change, this is no longer the case; forms that serve as chart definitions are classified with a special "CHART" encounter type, so they can be discovered without the use of any magic numbers.
Previously as well, there was a global property named `projectbuendia.chartUuids` that purported to identify which forms were charts, but in reality there was nothing to keep it consistent with the rest of the system, resulting in fragility like the possibility of an exception thrown when listing the available charts.  This dependency is now also eliminated.
All Buendia-specific objects that have UUIDs now have UUIDs that follow a recognizable pattern: their …

Eliminate the hardcoded chart UUID and establish a convention for other special UUIDs

---

packages/buendia-server/data/usr/share/buendia/config.d/70-server

Previously, server startup would take anywhere from 2 minutes to 15 minutes, regardless of the speed of the CPU—it could take 5 minutes on the Raspberry Pi yet well in excess of 10 minutes on the Intel NUC.  I finally discovered that this was due to Catalina's use of `/dev/random` to collect entropy for generating random session IDs, and ultimately due to the unfortunate Java design decision to make `/dev/random` the default source of entropy.
Symlinking `/dev/random` to `/dev/urandom` brings startup time down to consistently 1 minute.

Greatly accelerate startup by pointing /dev/random at /dev/urandom

---

tools/clear_tester.sql

Now that we can more easily manage multiple OpenMRS accounts, we can run all of our instrumented functional tests using a separate tester account, and then wipe the tester account without affecting anything else.  This SQL script accomplishes that reset.

Add a script that deletes everything created by a tester account.

---

packages/buendia-backup/data/etc/cron.d/buendia-backup
packages/buendia-pkgserver/data/etc/cron.d/buendia-pkgserver
packages/buendia-utils/data/usr/share/buendia/utils.sh

Both `buendia-update` and `buendia-pkgserver` perform a more or less indiscriminate scan of `/dev/sd??`, looking for block devices that appear to be suitable for external sources for update/backup/restore operations. On a NUC, this results in, for example, an attempt to mount the root of the main system partition once a minute, looking for non-existent backups.
This PR uses [`lsblk`](http://man7.org/linux/man-pages/man8/lsblk.8.html) to provide a common means for Buendia packages to identify external USB block devices, as well as a user-configurable override as needed (e.g. for automated testing).

Add a common means of searching for external block devices

---

openmrs/omod/src/main/java/org/openmrs/projectbuendia/Utils.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/VisitObsValue.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/servlet/DataExportServlet.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/LocationResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/Logger.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ObservationUtils.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/OrderResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/RequestLogger.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/XformInstanceResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/XmlUtil.java
openmrs/omod/src/test/java/org/openmrs/projectbuendia/webservices/rest/OrderResourceTest.java
openmrs/omod/src/test/java/org/openmrs/projectbuendia/webservices/rest/XformInstanceResourceTest.java
openmrs/omod/src/test/resources/org/openmrs/projectbuendia/webservices/rest/expected-grouped.xml
openmrs/omod/src/test/resources/org/openmrs/projectbuendia/webservices/rest/expected-instance-add.xml
openmrs/omod/src/test/resources/org/openmrs/projectbuendia/webservices/rest/expected-instance-edit.xml

With this change, no more database IDs are visible or expected as input or output in the server API, with the one exception of the XForm submission interface, over which we don't have direct control.
There are also several small fixes and improvements to logging.

Eliminate all internal database IDs from the API; clients need only to work with UUIDs.

---

openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/DbUtil.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/OrderResource.java
openmrs/omod/src/test/java/org/openmrs/projectbuendia/webservices/rest/PatientResourceTest.java

Previously, the patient identifier types (MSF and LOCAL) were assigned random UUIDs, and retrieved by name.  They now have readable UUIDs that follow our naming convention (`buendia_identifier_type_msf`, `buendia_identifier_type_local`).

Stable canonical UUIDs for identifier types.

---

openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/Logger.java
openmrs/omod/src/test/java/org/openmrs/projectbuendia/webservices/rest/BaseApiRequestTest.java
openmrs/omod/src/test/java/org/openmrs/projectbuendia/webservices/rest/LocationResourceTest.java
openmrs/omod/src/test/java/org/openmrs/projectbuendia/webservices/rest/OrderResourceTest.java
openmrs/omod/src/test/java/org/openmrs/projectbuendia/webservices/rest/PatientResourceTest.java
openmrs/omod/src/test/java/org/openmrs/projectbuendia/webservices/rest/XformResourceTest.java

This moves commonly duplicated code into a base class.

Introduce BaseApiRequestTest; use it to clean up the unit tests.

---

openmrs/omod/src/main/java/org/openmrs/projectbuendia/Utils.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/EncounterResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ObservationResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ObservationUtils.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/OrderResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/PatientResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/UserResource.java

Previously, we always created a Person and a User for every Provider, and moved back and forth among these three types of objects and three IDs when trying to associate edited or created objects with the user or person who did the editing or creating.  This was awkward and doesn't really fit how OpenMRS intended to store these relationships.
This PR clears that up.  Providers stand on their own, and correspond to the "users" we see on the client.  Providers can be referenced as the `orderer` on an order, or as the provider who took the observations in an encounter via the `encounter_provider` association table.
Users in OpenMRS are entities that have OpenMRS usernames and passwords.  This corresponds to the OpenMRS username and password configured in the client.  The `creator` and …

Assign user_ids and provider_ids to other objects correctly

---

packages/buendia-server/Makefile
tools/openmrs_account_setup
tools/openmrs_location_setup

This script automatically sets up a few simple locations.  With the addition of this script, deployment for smoke testing can now be automated with `buendia-openmrs-load`, `buendia-openmrs-account-setup`, `buendia-openmrs-location-setup`, and `buendia-profile-apply`.

Add openmrs_location_setup.

---

packages/buendia-tomcat7/control/postinst
packages/buendia-tomcat7/data/usr/share/buendia/diversions/etc/tomcat7/context.xml
tools/clear_server.sql
tools/package_grep

This adds a few sundry fixes:
- `package_grep` used to not search the `Makefile` for the package; now it does.
- `clear_server.sql` used to delete the large `concept_reference_map`, `concept_reference_term`, and `concept_word` tables; now it no longer needs to do that because we have a tested, known-working database dump that omits the contents of these tables.
- When `tomcat7` started up, Catalina would often spew error messages about unrestorable sessions.  We don't need to preserve user sessions across restarts of `tomcat7`, so this change disables that feature.

Various improvements to scripts

---

tools/profile_apply

Instead of complaining when form UUIDs might collide, ensure that they never collide by appending a number to the end of any potential duplicates.

Prevent collisions between generated form UUIDs.

---

openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ChartResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ConceptResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/DbUtils.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/XformResource.java

Previously we only returned information for concepts that exist in the charts.  This didn't include concepts that are used in the form but not explicitly mentioned in the chart, such as pregnancy status; for those concepts, observations would not update immediately on the client but would have to wait until the next sync.  With this fix, pregnancy status updates immediately on the client when the form is submitted.

Return all concepts in forms as well as charts.

---

packages/buendia-dashboard/control/postinst
packages/buendia-dashboard/data/etc/logrotate.d/buendia-dashboard
packages/buendia-dashboard/data/usr/share/buendia/tests/40-dashboard-running

Now `/var/log/large/requests` exists whenever `buendia-dashboard` is installed and furthermore is `chmod 1777` so that Catalina can write to it.
This was driven partly because the integration tests for `buendia-dashboard` were failing because we very wisely made `set -e` the [default for integration tests](https://github.com/projectbuendia/buendia/commit/3b09f23f8). Now we can remove that **FIXME** from the test! :confetti_ball: 
@zestyping I think this is pretty uncontroversial, so I'm going to wait a lil bit and then merge, unless I hear back from you.

Ensure that /var/log/{large/,}requests is world-writeable

---

packages/buendia-dashboard/control/control.template
packages/buendia-monitoring/data/etc/cron.d/buendia-monitoring
packages/buendia-monitoring/data/usr/share/buendia/tests/40-monitoring-logs-safe
packages/buendia-utils/data/usr/bin/buendia-status

The classic `ifconfig` utility has been replaced in Debian 9 by the `ip` utility. This PR updates the monitoring and dashboard packages to dump diagnostic data from `ip` instead.
Also, the `dashboard` package relies on the `monitoring` package for a number of things, not the least the correct setup of `/var/log/large/requests` et cetera, so this dependency has been made explicit.

Update monitoring and dashboard packages to rely on ip, not ifconfig

---

packages/buendia-pkgserver/data/etc/apt/sources.list.d/buendia-pkgserver.list
packages/buendia-site-demo/data/etc/apt/sources.list.d/buendia.list
packages/buendia-site-dev/data/etc/apt/sources.list.d/buendia.list
packages/buendia-site-lon/data/etc/apt/sources.list.d/buendia.list
packages/buendia-site-msf-chad-bokoro/data/etc/apt/sources.list.d/buendia.list
packages/buendia-site-msf-geneva/data/etc/apt/sources.list.d/buendia.list
packages/buendia-site-msf-ks/data/etc/apt/sources.list.d/buendia.list
packages/buendia-site-msf-mg/data/etc/apt/sources.list.d/buendia.list
packages/buendia-site-test/data/etc/apt/sources.list.d/buendia.list
packages/tests/check-filenames

Having an apt source pointing to `localhost:9001` just causes useless errors unless pkgserver is installed. Instead, let's have `buendia-pkgserver` provide its own sources.list, and add `buendia-pkgserver` as a dependency back to those site packages that need it.

Move pkgserver sources.list to pkgserver.

---

openmrs/omod/src/main/java/org/openmrs/projectbuendia/Utils.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/BaseResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ChartResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ConceptResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/DbUtils.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/EncounterResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ItemNotFoundException.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/LocationResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/ObservationResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/OrderResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/PatientResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/UserResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/UuidNotFoundException.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/XformInstanceResource.java
openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/XformResource.java
openmrs/omod/src/main/java/org/projectbuendia/openmrs/webservices/rest/RestController.java
tools/rest

The new REST client utility, `tools/rest`, can make GET or POST requests to a REST endpoint, and pretty-prints the results to make them easier to read.  This change goes hand-in-hand with a change to the error reporting format that makes errors much easier to understand in the `tools/rest` output.

Make REST error output more readable and add a REST client utility

---

openmrs/omod/src/main/java/org/openmrs/projectbuendia/webservices/rest/OrderResource.java

Previously, null fields were ignored.  But when an order is updated, null fields should overwrite the existing values.

Allow updates to replace order fields with null.

---

packages/buendia-networking/data/usr/share/buendia/site/10-networking
packages/buendia-site-reference/Makefile
packages/buendia-site-reference/control/control.template
packages/buendia-site-reference/control/postinst
packages/buendia-site-reference/data/usr/share/buendia/packages.list.d/site
packages/buendia-site-reference/data/usr/share/buendia/site/40-site
tools/iso/preseed.cfg

The reference deployment consists of a NanoStation M2 on 10.0.0.1/24, providing DHCP with the DNS server set to 10.0.0.2. The wifi SSID is `buendia`.
This package configures the NUC to take 10.0.0.2/24 on its wifi interface, and provide DNS on that address.
The Wi-Fi password should be set manually by adding a `NETWORKING_PASSWORD` parameter to `/usr/share/buendia/site/75-networking` or similar.

Add buendia-site-reference package

---

packages/buendia-backup/data/usr/bin/buendia-backup
packages/buendia-backup/data/usr/bin/buendia-db-is-empty
packages/buendia-backup/data/usr/bin/buendia-db-is-unused
packages/buendia-backup/data/usr/bin/buendia-restore
packages/buendia-backup/data/usr/share/buendia/tests/20-backup-skip-safe
packages/buendia-backup/data/usr/share/buendia/tests/50-backup-locked-safe
packages/buendia-backup/data/usr/share/buendia/tests/60-backup-and-restore

This PR changes the behavior of `buendia-restore` to restore the latest directory from an external block device that matches the format _backup.YYYY-MM-DD_, but only if the current database has no patient entries.
Also the behavior of `buendia-backup` is changed to refrain from creating backups _unless_ the database has patient entries.
For this purpose is included is a utility shell script `buendia-db-is-unused` which returns true if and only if the database contains exactly zero patient records.
The integration tests have been updated to confirm the new behavior.

Restore automatically restores any backup if the current database has never been used

---

packages/buendia-backup/data/usr/bin/buendia-restore
packages/buendia-dashboard/data/usr/share/buendia/dashboard/client
packages/buendia-dashboard/data/usr/share/buendia/dashboard/index
packages/buendia-networking/data/usr/bin/buendia-update-hosts
packages/buendia-networking/data/usr/share/buendia/names.d/README
packages/buendia-ntpserver/data/usr/share/buendia/names.d/ntpserver
packages/buendia-pkgserver/data/usr/share/buendia/names.d/pkgserver
packages/buendia-pkgserver/data/usr/share/buendia/site/10-pkgserver
packages/buendia-server/data/usr/share/buendia/names.d/server

Earlier versions of buendia allowed packages to specify different hostnames it wanted the host to serve via DNS, e.g. `packages` or `server`, by means of files in `/usr/share/buendia/names.d` which would be read by `buendia-networking` when configuring the network stack. This seems unnecessary and fragile with our current setup.
This PR removes this feature from `buendia-networking` and updates it to provide two hostnames `buendia` and `buendia.local` on the local network when serving DNS.

Have the server use a single hostname: `buendia`

---

.circleci/config.yml
packages/buendia-backup/data/usr/share/buendia/tests/50-backup-locked-safe
packages/buendia-backup/data/usr/share/buendia/tests/60-backup-and-restore

Now that we have a separate demo server, we can run the integration tests on `staging.buendia.org` on every dev build, so that we get an alert (via the CircleCI Slack integration) if the tests ever fail.
This PR splits out the CircleCI tasks of deploying new packages to the download and staging servers for clarity, and adds a final call to the staging server via SSH to run the tests.
Also included are two small fixes to the `buendia-backup` tests for previously-untested and race conditions.

Run integration tests on staging after every dev build.

---

packages/buendia-server/data/usr/share/buendia/config.d/70-server
packages/buendia-tomcat7/data/usr/share/buendia/diversions/etc/default/tomcat7

We've experienced slow server startup times in the past, due to a [fairly well-known issue](https://ruleoftech.com/2016/avoiding-jvm-delays-caused-by-random-number-generation) with Catalina blocking while looking for randomness.
In 1562e92, we tackled this issue by replacing `/dev/random` with `/dev/urandom`; however, this approach has two disadvantages: One, the PRNG devices are replaced by Debian on boot; two, it addresses a JVM "bug" by making a system-wide change with possible unintended consequences.
This PR addresses the problem a little more directly by explicitly telling the JVM which PRNG to use when starting Catalina. The use of `/dev/./urandom` (_sic_) apparently sidesteps some cleverness internal to the JVM that we evidently _don't_ want.

Use Java options to prevent slow Tomcat startup

---

.circleci/config.yml
packages/buendia-site-cloud-demo/data/usr/share/buendia/site/40-site
packages/buendia-site-test-integration/data/usr/share/buendia/site/40-site
packages/buendia-update/data/usr/bin/buendia-update
packages/buendia-update/data/usr/share/buendia/site/10-update

Per @zestyping's [outline](https://buendia.slack.com/archives/C02T5LNMC/p1568690670015500), this PR adds a step to `buendia-update` which completely refreshes the database on demand, if migration to the latest version is not possible.
This feature is enabled with the `UPDATE_FORCE_UPGRADE` site setting and it **will destroy whatever is in the database** after backing up to `/var/backups/buendia`. Therefore this setting should be used _only_ on demo or testing sites where the contents of the database are not valuable.
This setting is enabled by default in the `buendia-site-cloud-demo` and `buendia-site-test-integration` sites.
This PR also includes a change to CI to use `buendia-update` to upgrade packages on the staging site.

Add automatic forced database upgrades when migration fails.

---

packages/buendia-networking/control/control.template
packages/buendia-networking/data/usr/bin/buendia-update-hosts

Previously buendia-update-hosts would overwrite `/etc/hosts` and restart dnsmasq whenever it was run, which is currently every minute via cron job. Now it uses diff(1) to see if it has made any substantive changes before overwriting the file and restarting the daemon.
Tested manually. Fixes #222.

buendia-update-hosts restarts dnsmasq only when changes are detected.

---

packages/buendia-tomcat7/data/usr/share/buendia/diversions/etc/tomcat7/server.xml

We discovered, as reported in #225, that Tomcat 7 apparently creates a new session for (nearly?) every API request, and then hangs onto these sessions for a half hour, which can cause heavy usage of the Buendia client to cause `OutOfMemory` errors on the server.
This PR uses the stock `CrawlerSessionManagerValve` that comes with Tomcat 7 to synthesize a session ID for those clients who don't return one in a cookie. It's designed to make Tomcat more resilient to crawler requests, but it works just as well for us too. The consequence is that the JVM heap no longer grows with each API request.
Configuration of CrawlerSessionManagerValve is documented in the [Tomcat API reference](http://tomcat.apache.org/tomcat-7.0-doc/config/valve.html#Crawler_Session_Manager_Valve). Results from manual …

Use CrawlerSessionManagerValve to keep API clients from blowing up the Tomcat session cache.

---

packages/buendia-tomcat7/data/usr/share/buendia/diversions/etc/tomcat7/server.xml

The IP-address-based Tomcat session reuse enabled by
`CrawlerSessionManagerValve` in #230 unfortunately permits the following scenario:
1. Client A uses HTTP Basic Auth to authenticate to the API.
2. Client A departs from the network.
3. Client B connects to the API within 5 minutes, using the same IP address and user agent string as Client A, but without authenticating.
4. Client B is assigned Client A's session by `CrawlerSessionManagerValve`
and is now using Client A's credentials.
I think we can agree that this is not what we intended. Unfortunately I think it means we need to reopen #225 and come up with a more robust solution.

Revert PR #230 as authenticating under CrawlerSessionManagerValve opens a security risk

---

packages/buendia-dashboard/data/usr/share/buendia/tests/40-dashboard-running-safe

The changes to the dashboard URLs introduced in #231 broke the dashboard integration tests, and hence our CI pipeline. This PR fixes the tests to match the new functionality.
I take the fact that we didn't act on this information promptly as an indication that we should revisit the integration tests and pipeline to see what we need to make them useful to us as developers.
Merging because changes are purely test related. Tagging @zestyping FYI

Fix dashboard auth test that was broken by PR #231

---

openmrs/api/src/main/java/org/projectbuendia/openmrs/api/ProjectBuendiaService.java
openmrs/api/src/main/java/org/projectbuendia/openmrs/api/impl/ProjectBuendiaServiceImpl.java
packages/buendia-server/data/usr/share/buendia/tests/30-server-auth-safe

Fixes #223 by adding `@Authorized` annotations to `ProjectBuendiaService`, following the example of `org.openmrs.api.PatientService` in [OpenMRS 1.10.x](https://github.com/openmrs/openmrs-core/blob/1.10.x/api/src/main/java/org/openmrs/api/PatientService.java#L148-L150).
Includes integration tests to confirm working functionality. These tests pass for me in Vagrant.

Ensure that API methods that rely on ProjectBuendiaService get authenticated

---

packages/buendia-pkgserver/data/usr/bin/buendia-pkgserver-import

Minor change to `buendia-pkgserver-import` prevents the creation of working directories that are then not deleted when the script discovers that there's nothing to import. Fixes #237.

Delay creation of buendia-pkgserver-import working directories.

---

packages/buendia-utils/control/postinst
packages/buendia-utils/data/lib/systemd/system/buendia-init.service
packages/buendia-utils/data/usr/bin/buendia-init

Closes: #226 
If the internal battery power is lost, it will reset the hardware clock.  To prevent the resulting catastrophic failure (which we experienced once during a demo in Bunia), this PR checks for this condition on boot and disables the Buendia API.  This doesn't automatically fix the problem, but at least we can fail safely and obviously so that a human will be prompted to investigate immediately.

Check the hwclock on boot and disable the Buendia API if it has moved backwards since the last shutdown.

---

packages/buendia-backup/data/usr/bin/buendia-backup

`buendia-backup` assumes that certain directories exist when the Buendia configuration is backed up, and fails with an error if not. However, if those directories don't exist, there's nothing to back up per se -- this is definitely not a fatal error and shouldn't be treated as such.
This small change to `buendia-backup` addresses this situation and fixes #207.

Fix errors in buendia-backup when certain config paths don't exist yet.

---

openmrs/omod/src/main/java/org/projectbuendia/openmrs/webservices/rest/RestController.java

Since REST clients don't reuse Java servlet HTTP sessions, make sure that we always invalidate the current session (if any), to prevent the session cache from filling up and bogging down the servlet container.
Tested using `tools/stress` and `jmap -histo:live` as described in the [comments to #225](https://github.com/projectbuendia/buendia/issues/225#issuecomment-543907168). The `jmap` output looks good after 11,000 requests, and request response times are nominal.
Has no impact on regular user logins via the web interface. Tested by logging into OpenMRS and then waiting 20 minutes to see if I was still logged in, as expected.
Ran the integration tests manually in Vagrant. All pass.
Fixes #225 hopefully once and for all.

Discard HTTP sessions during RestController.finish()

---

packages/buendia-networking/data/usr/share/buendia/config.d/10-networking

Fixes a logic bug introduced in refactoring in 5cbf09793.

(Actually) exit early if we have no interfaces to configure.

---

packages/buendia-networking/control/control.template
packages/buendia-networking/control/postinst
packages/buendia-networking/control/prerm
packages/buendia-networking/data/usr/share/buendia/config.d/10-networking

Use of `dhcpcd` was added in 14bfde71 back in June, but it was never implemented in such a way as to replace `dhclient` (which Debian uses by default when implementing `/etc/network/interfaces`).
The vestiges of this change resulted in `dhcpcd` periodically and unexpectedly requesting DHCP leases on interfaces when `buendia-networking` was not configured to do so. This PR removes dhcpcd support from `buendia-networking`.
Tested by rebooting a NUC repeatedly with site settings configured for either DHCP or static IP addresses on the Wi-Fi and ensuring that DHCP leases are only requested when `buendia-networking` is configured for it.
Also included is a minor fix to ensure that `buendia-monitoring` is present since `buendia-wifi-watchdog` is run by `cron` using `buendia-log`.

Remove dhcpcd usage from buendia-networking

---

packages/buendia-networking/data/usr/bin/buendia-wifi-watchdog

Add `NETWORKING_WATCHDOG_MIN_UPTIME` setting to `buendia-wifi-watchdog`, and default to 15s, as a workaround to shorten latency on wifi initialization on the NUC. This delay was chosen after observing system network configuration on the NUC to not take longer than 7-8s from kernel boot via syslogs from a number of Buendia installations.
Tested fairly extensively on the NUC with Wi-Fi both on static and DHCP-assigned addresses.
Improves the situation with #246 but is perhaps not a permanent fix.

Shorten buendia-wifi-watchdog delay to ensure that Wi-Fi comes up faster

---

packages/buendia-networking/data/usr/share/buendia/config.d/10-networking

Add a file mutex to the `config.d/10-networking` script in `buendia-networking`, to ensure that only one network reconfiguration can be run at a time.
This addresses potential race conditions where `buendia-wifi-watchdog` attempts to restart the Wi-Fi connection while another similar watchdog process is already waiting on, e.g., a slow DHCP server.

Prevent simultaneous network reconfigurations
